# filepath: C:\Users\sprim\dotfiles\PowerShell\Modules\Aliases\Aliases.psm1
# PowerShell Custom Aliases and Functions Module
# Version: 2.0
# Last Modified: July 02, 2025
# Description: Loads functions from individual files and sets aliases.
# This file is auto-generated by Update-AliasesModule.ps1

# Get the path to the current module directory
$ModulePath = Split-Path -Parent $MyInvocation.MyCommand.Definition
Write-Verbose "Loading functions from module path: $ModulePath"

# Dot-source individual function script files
try {
    . "$ModulePath\Find-Directory.ps1"
    . "$ModulePath\Find-Text.ps1"
    . "$ModulePath\Get-AliasHelp.ps1"
    . "$ModulePath\Get-FileSize.ps1"
    . "$ModulePath\Get-FileTree.ps1"
    . "$ModulePath\Get-GitStatus.ps1"
    . "$ModulePath\Get-NetworkConnections.ps1"
    . "$ModulePath\Get-ProjectList.ps1"
    . "$ModulePath\Get-SecretKey.ps1"
    . "$ModulePath\Get-SystemInfo.ps1"
    
    . "$ModulePath\Invoke-UpdateAliasesModule.ps1"
    . "$ModulePath\New-GitCommit.ps1"
    . "$ModulePath\Open-Explorer.ps1"
    . "$ModulePath\Set-ProjectRoot.ps1"
    . "$ModulePath\Show-Json.ps1"
    . "$ModulePath\Stop-ProcessByPort.ps1"
    . "$ModulePath\Test-NewFunction.ps1"
    . "$ModulePath\Test-Port.ps1"
    . "$ModulePath\Update-AliasesModule-Function.ps1"
    . "$ModulePath\Update-AliasesModuleFunction.ps1"
    . "$ModulePath\Update-EnvVars.ps1"
    Write-Verbose "Successfully dot-sourced function files."
}
catch {
    Write-Error "Failed to dot-source one or more function files: $_"
    return
}

# Define Aliases
try {
    Set-Alias -Name finddir -Value Find-Directory -Description "Quickly find and navigate to directories by partial name." -Scope Global -Force
    Set-Alias -Name grep -Value Find-Text -Description "Search for text in files with colored output." -Scope Global -Force
    Set-Alias -Name aliashelp -Value Get-AliasHelp -Description "Lists all aliases defined in this module with their descriptions or function synopses." -Scope Global -Force
    Set-Alias -Name sizes -Value Get-FileSize -Description "Show file sizes in human readable format." -Scope Global -Force
    Set-Alias -Name filetree -Value Get-FileTree -Description "Displays a tree view of a directory structure." -Scope Global -Force
    Set-Alias -Name gs -Value Get-GitStatus -Description "Quick git status with branch info and clean output." -Scope Global -Force
    Set-Alias -Name netstat -Value Get-NetworkConnections -Description "Show active network connections." -Scope Global -Force
    Set-Alias -Name projects -Value Get-ProjectList -Description "Find all package.json and pyproject.toml files and show project structure." -Scope Global -Force
    Set-Alias -Name gensecret -Value Get-SecretKey -Description "Generates a cryptographically secure URL-safe string." -Scope Global -Force
    Set-Alias -Name sysinfo -Value Get-SystemInfo -Description "Show system resources and running processes." -Scope Global -Force
    
    Set-Alias -Name updatealiases -Value Invoke-UpdateAliasesModule -Description "Completely regenerates the Aliases module and profile lazy-loading functions." -Scope Global -Force
    Set-Alias -Name gc -Value New-GitCommit -Description "Quick commit with message prompt." -Scope Global -Force
    Set-Alias -Name explore -Value Open-Explorer -Description "Open current directory in Windows Explorer." -Scope Global -Force
    Set-Alias -Name projectroot -Value Set-ProjectRoot -Description "Changes the current location to a specified project directory." -Scope Global -Force
    Set-Alias -Name json -Value Show-Json -Description "Pretty print JSON files with syntax highlighting." -Scope Global -Force
    Set-Alias -Name killport -Value Stop-ProcessByPort -Description "Kill processes by port number." -Scope Global -Force
    Set-Alias -Name testnewfunction -Value Test-NewFunction -Description "Alias for Test-NewFunction" -Scope Global -Force
    Set-Alias -Name testport -Value Test-Port -Description "Test if a port is open on localhost or remote host." -Scope Global -Force
    Set-Alias -Name aliasesmodule-function -Value Update-AliasesModule-Function -Description "Alias for Update-AliasesModule-Function" -Scope Global -Force
    Set-Alias -Name aliasesmodulefunction -Value Update-AliasesModuleFunction -Description "Alias for Update-AliasesModuleFunction" -Scope Global -Force
    Set-Alias -Name updateenv -Value Update-EnvVars -Description "Updates or creates a user-level environment variable persistently." -Scope Global -Force
    Write-Verbose "Successfully set aliases."
}
catch {
    Write-Error "Failed to set one or more aliases: $_"
}

# Export all public functions and their aliases from this module
Export-ModuleMember -Function Find-Directory, Find-Text, Get-AliasHelp, Get-FileSize, Get-FileTree, Get-GitStatus, Get-NetworkConnections, Get-ProjectList, Get-SecretKey, Get-SystemInfo, Invoke-UpdateAliasesModule, New-GitCommit, Open-Explorer, Set-ProjectRoot, Show-Json, Stop-ProcessByPort, Test-NewFunction, Test-Port, Update-AliasesModule-Function, Update-AliasesModuleFunction, Update-EnvVars `
    -Alias finddir, grep, aliashelp, sizes, filetree, gs, netstat, projects, gensecret, sysinfo, updatealiases, gc, explore, projectroot, json, killport, testnewfunction, testport, aliasesmodule-function, aliasesmodulefunction, updateenv

Write-Verbose "Aliases module loaded successfully."
