# Auto-generated by scripts/add-cross-shell-tool.sh
# Adds uv to PATH when available.

$toolDir = Get-UserProfilePath -Segments @('.local','bin')
if (Test-Path -LiteralPath $toolDir) {
    Add-PathIfMissing -Path $toolDir
}
