# Windows PowerShell 7 Profile - Generated by dotfiles setup
# Created: 2025-09-06T21:59:19-04:00
# This profile loads the main dotfiles PowerShell configuration from WSL2.

# Prefer \wsl.localhost, then legacy \wsl$ fallback
$roots = @(
  "\\wsl.localhost\Ubuntu-24.04\home\sprime01\dotfiles",
  "\\wsl.localhost\Ubuntu-24.04\home\sprime01\dotfiles" -replace '^\\\\wsl\.localhost', '\\wsl$'
)

# Resolve DOTFILES_ROOT and main profile
foreach ($r in $roots) {
  $candidate = Join-Path $r 'PowerShell\Microsoft.PowerShell_profile.ps1'
  if (Test-Path $candidate) {
    $env:DOTFILES_ROOT = $r
    break
  }
}
if (-not $env:DOTFILES_ROOT) { $env:DOTFILES_ROOT = "\\wsl.localhost\Ubuntu-24.04\home\sprime01\dotfiles" }
if (-not $env:PROJECTS_ROOT) { $env:PROJECTS_ROOT = "C:\Users\sprim\projects" }

$mainProfile = Join-Path $env:DOTFILES_ROOT 'PowerShell\Microsoft.PowerShell_profile.ps1'
if (Test-Path $mainProfile) {
  try {
    . $mainProfile
    Write-Host '✅ Loaded dotfiles PowerShell profile' -ForegroundColor Green
  } catch {
    Write-Warning '❌ Error loading dotfiles PowerShell profile:'
    Write-Warning $_.Exception.Message
    Write-Host '💡 Falling back to basic configuration' -ForegroundColor Yellow
    function projects { Set-Location $env:PROJECTS_ROOT }
  }
} else {
  Write-Warning ("Dotfiles main profile not found at: " + $mainProfile)
  Write-Host '📦 Setting up basic configuration...' -ForegroundColor Yellow
  function projects { Set-Location $env:PROJECTS_ROOT }
}