#!/usr/bin/env bash
# scripts/windows-chezmoi-diff.sh — Show chezmoi diff on Windows from WSL using this repo as source
# Usage: windows-chezmoi-diff.sh [SOURCE_DIR]

set -euo pipefail

SRC_DIR="${1:-$HOME/dotfiles}"

echo "🪟 Chezmoi diff (Windows) from WSL"

if [[ -z "${WSL_DISTRO_NAME:-}" ]]; then
	echo "❌ This helper is intended to run inside WSL." >&2
	exit 2
fi

if [[ ! -d "$SRC_DIR" ]]; then
	echo "❌ Source directory not found: $SRC_DIR" >&2
	exit 2
fi

# Validate and remediate .chezmoiignore in source (destination-based patterns)
SRC_IGNORE="$SRC_DIR/.chezmoiignore"
if [[ -f "$SRC_IGNORE" ]]; then
	if grep -qE '^!dot_\*' "$SRC_IGNORE" 2>/dev/null; then
		echo "⚠️  Invalid pattern in $SRC_IGNORE: !dot_* (patterns match destination paths). Updating whitelist."
		cp "$SRC_IGNORE" "$SRC_IGNORE.bak.$(date +%s)" 2>/dev/null || true
		cat >"$SRC_IGNORE" <<'EOF'
# Autogenerated minimal whitelist for destination paths
*
!.chezmoiignore
!.*
!.*/**
EOF
	fi
fi

if ! command -v powershell.exe >/dev/null 2>&1 && ! command -v pwsh.exe >/dev/null 2>&1; then
	echo "❌ powershell.exe / pwsh.exe not found from WSL." >&2
	exit 3
fi

UNC="\\\\wsl.localhost\\${WSL_DISTRO_NAME}$(printf '%s' "$SRC_DIR" | sed 's#^/#\\#; s#/#\\#g')"

PSBIN="pwsh.exe"
command -v pwsh.exe >/dev/null 2>&1 || PSBIN="powershell.exe"

PS_TMP="$(mktemp --suffix=.ps1)"
cat >"$PS_TMP" <<'EOF'
param(
  [Parameter(Mandatory=$true)][string]$Src
)
Write-Host "🔍 Diff Chezmoi from source: $Src" -ForegroundColor Cyan
if (-not (Get-Command chezmoi.exe -ErrorAction SilentlyContinue)) {
  Write-Warning "chezmoi.exe not found on Windows PATH. Install with: choco install chezmoi or winget install chezmoi"
  exit 4
}
try {
  chezmoi.exe diff --source $Src
  exit $LASTEXITCODE
} catch {
  Write-Error $_.Exception.Message
  exit 5
}
EOF
PS_TMP_WIN="$(wslpath -w "$PS_TMP")"
"$PSBIN" -NoProfile -ExecutionPolicy Bypass -File "$PS_TMP_WIN" -Src "$UNC"
rc=$?
rm -f -- "$PS_TMP" || true
exit $rc
