name: CI

on:
  push:
    branches: [ main, fix/**, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install shellcheck & shfmt (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck curl
          # Use the raw linux/amd64 shfmt binary (no tarball) and make it executable
          curl -sSLo /usr/local/bin/shfmt https://github.com/mvdan/sh/releases/download/v3.7.0/shfmt_v3.7.0_linux_amd64
          sudo chmod +x /usr/local/bin/shfmt
      - name: Install shellcheck & shfmt (macOS)
        if: contains(matrix.os, 'macos')
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install shellcheck shfmt || {
            echo "brew install failed"; exit 1;
          }
      - name: Run lint
        run: bash tools/lint.sh
      - name: Run tests
        run: bash scripts/run-tests.sh
